### ISSUE TITLE
changing file name descriptions

### ISSUE THREAD

**Issue by anfederman** [UbiquityRobotics/breadcrumb_learn#10]
1.jpg
Added tower assmebly
yesterday
angle_parts.jpg
Added tower assmebly
yesterday
angle_parts.png
Added tower assmebly

**Comment by JanezCim** [comment]
I see, this is about the changes you already made. Nice! And next time it would really be better if you make a PR with this, issues are reserved for issues and questions, while PRs are for exactly this kind of information
