### ISSUE TITLE
Breadcrumb learn corrections/improvements

### ISSUE THREAD

**Issue by GreTimotej** [UbiquityRobotics/breadcrumb_learn#25]
- [x] In [Assembly process](https://github.com/UbiquityRobotics/breadcrumb_learn/blob/master/ConveyorBot/shell_tower/shell_tower_assembly.md#assembly-process) step two, I would change "INTO THE LEFT MOLEX" to "INTO THE RIGHT MOLEX", so there is no confusion between the text and the picture.
- [x] The same should be done on the section with LIDAR mounting. Instead of "In this tutorial we are going to mount it on the left side of the shell", "In this tutorial we are going to mount it on the right side of the shell" would be more appropriate with the attached image.
- [ ] Assembly Process step 4: The green arrow on the picture might confuse someone with pointing directly at the screw hole that is not of importance here
- [x] Put the shell on the robot. Maybe add here to look for the cables, so we don't grit the cable between the shell and Magni. What do I do with the LIDAR cable that I pulled thorough the hole in Magni. It can get stuck between the shell and the front wheel. Might be tricky to get it out if we notice to late.
- [x] Step 6: plug the switch cables. Maybe make sure that the pointy side of connector is turned against MCB?
- [x] Step 8: It's easier if the back screws are first put into LIDAR holes and the put and screwed into the screw holes.
- [x] [Tower assembly](In this tutorial we are going to mount it on the left side of the shell) Step 1&2: weird language. Grammar mistakes
- [x] [Connecting tower to shell](In this tutorial we are going to mount it on the left side of the shell) Step 2: Maybe say something about optimal cable management.
- [x] Maybe put the BOM list on top of the page, so the user looks at what is available before assembling?
- [x] IDEA - floating side with screw pictures and descriptions.

**Comment by anfederman** [comment]
Right left is confusing since we don't know it is from the robot's or
user's viewpoint. Just say " as in the image."

**Comment by JanezCim** [comment]
> The same should be done on the section with LIDAR mounting. Instead of "In this tutorial we are going to mount it on the left side of the shell", "In this tutorial we are going to mount it on the right side of the shell" would be more appropriate with the attached image.

Beacause we are using notation "shell_left" in the code where mentioning what position the lidar is in, im going to insert extra text to explan what right/left here means instead of just deleting this out. This will come handy later for the user

**Comment by JanezCim** [comment]
> IDEA - floating side with screw pictures and descriptions.

That would be great! But i dont think I have this option with the github pages. In terms of "advanced"  features like that its pretty limited
